// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240111.5

#pragma once
#ifndef WINRT_OpenDirectoryExt_H
#define WINRT_OpenDirectoryExt_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.240111.5"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.240111.5"
#include "winrt/impl/OpenDirectoryExt.2.h"
namespace winrt::impl
{
    template <typename D>
    struct produce<D, winrt::OpenDirectoryExt::IClass> : produce_base<D, winrt::OpenDirectoryExt::IClass>
    {
    };
}
WINRT_EXPORT namespace winrt::OpenDirectoryExt
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::OpenDirectoryExt::IClass> : winrt::impl::hash_base {};
    template<> struct hash<winrt::OpenDirectoryExt::Class> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
