// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240111.5

void* winrt_make_OpenDirectoryExt_Class()
{
    return winrt::detach_abi(winrt::make<winrt::OpenDirectoryExt::factory_implementation::Class>());
}
WINRT_EXPORT namespace winrt::OpenDirectoryExt
{
    Class::Class() :
        Class(make<OpenDirectoryExt::implementation::Class>())
    {
    }
}
