// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240111.5

#pragma once
#ifndef WINRT_OpenDirectoryExt_2_H
#define WINRT_OpenDirectoryExt_2_H
#include "winrt/impl/OpenDirectoryExt.1.h"
WINRT_EXPORT namespace winrt::OpenDirectoryExt
{
    struct WINRT_IMPL_EMPTY_BASES Class : winrt::OpenDirectoryExt::IClass
    {
        Class(std::nullptr_t) noexcept {}
        Class(void* ptr, take_ownership_from_abi_t) noexcept : winrt::OpenDirectoryExt::IClass(ptr, take_ownership_from_abi) {}
        Class();
    };
}
#endif
