// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240111.5

#pragma once
#ifndef WINRT_OpenDirectoryExt_1_H
#define WINRT_OpenDirectoryExt_1_H
#include "winrt/impl/OpenDirectoryExt.0.h"
WINRT_EXPORT namespace winrt::OpenDirectoryExt
{
    struct WINRT_IMPL_EMPTY_BASES IClass :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IClass>
    {
        IClass(std::nullptr_t = nullptr) noexcept {}
        IClass(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
